// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character interface {
	IsCharacter()
}

type Droid struct {
	Name            string `json:"name"`
	PrimaryFunction string `json:"primaryFunction"`
	Class						string `json:"class"`
	Colour					string `json:"colour"`
}

func (Droid) IsCharacter() {}

type Human struct {
	Name          string `json:"name"`
	HasLightsaber bool   `json:"hasLightsaber"`
	Class					string `json:"class"`
	Colour				string `json:"colour"`
}

func (Human) IsCharacter() {}
